//USER TYPES
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const REMOVE_USER = 'REMOVE_USER';

//TOKEN TYPES
export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL';

//GROUP TYPES
export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const GET_LIST_GROUP = 'GET_LIST_GROUP';
export const GET_LIST_GROUP_SUCCESS = 'GET_LIST_GROUP_SUCCESS';
export const GET_LIST_GROUP_FAIL = 'GET_LIST_GROUP_FAIL';

//LIST USER TYPES
export const GET_LIST_USER = 'GET_LIST_USER';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_FAIL = 'GET_LIST_USER_FAIL';

//TIME TYPES
export const UPDATE_FREETIME = 'UPDATE_FREETIME';
export const UPDATE_FREETIME_SUCCESS = 'UPDATE_FREETIME_SUCCESS';
export const UPDATE_FREETIME_FAIL = 'UPDATE_FREETIME_FAIL';

//LOCATION TYPES
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAIL = 'UPDATE_LOCATION_FAIL';
